[2023-09-18T13:54:48.393+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-09-08T00:00:00+00:00 [queued]>
[2023-09-18T13:54:48.467+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-09-08T00:00:00+00:00 [queued]>
[2023-09-18T13:54:48.471+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:54:48.569+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task2> on 2023-09-08 00:00:00+00:00
[2023-09-18T13:54:48.634+0000] {standard_task_runner.py:57} INFO - Started process 5259 to run task
[2023-09-18T13:54:49.501+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoring', 'task2', 'scheduled__2023-09-08T00:00:00+00:00', '--job-id', '447', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmp46ist9hn']
[2023-09-18T13:55:00.145+0000] {standard_task_runner.py:85} INFO - Job 447: Subtask task2
[2023-09-18T13:55:11.614+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 447 for task task2 ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 5259)
[2023-09-18T13:55:12.925+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-18T13:55:13.030+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
