[2023-09-19T13:02:18.425+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-04T00:00:00+00:00 [queued]>
[2023-09-19T13:02:18.435+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-04T00:00:00+00:00 [queued]>
[2023-09-19T13:02:18.436+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-19T13:02:18.454+0000] {taskinstance.py:1380} INFO - Executing <Task(FileSensor): waiting_file> on 2023-09-04 00:00:00+00:00
[2023-09-19T13:02:18.460+0000] {standard_task_runner.py:57} INFO - Started process 1047 to run task
[2023-09-19T13:02:18.463+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '7.3-externalTaskSensor', 'waiting_file', 'scheduled__2023-09-04T00:00:00+00:00', '--job-id', '600', '--raw', '--subdir', 'DAGS_FOLDER/7.3-ExternalTaskSensor.py', '--cfg-path', '/tmp/tmpztcu5xps']
[2023-09-19T13:02:18.464+0000] {standard_task_runner.py:85} INFO - Job 600: Subtask waiting_file
[2023-09-19T13:02:18.512+0000] {task_command.py:415} INFO - Running <TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-04T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-19T13:02:18.595+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='7.3-externalTaskSensor' AIRFLOW_CTX_TASK_ID='waiting_file' AIRFLOW_CTX_EXECUTION_DATE='2023-09-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-04T00:00:00+00:00'
[2023-09-19T13:02:18.617+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/filesystem.py", line 61, in poke
    hook = FSHook(self.fs_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/filesystem.py", line 38, in __init__
    conn = self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
[2023-09-19T13:02:18.623+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=7.3-externalTaskSensor, task_id=waiting_file, execution_date=20230904T000000, start_date=20230919T130218, end_date=20230919T130218
[2023-09-19T13:02:18.636+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 600 for task waiting_file (The conn_id `fs_default` isn't defined; 1047)
[2023-09-19T13:02:18.675+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-19T13:02:18.696+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-19T13:38:50.016+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-04T00:00:00+00:00 [queued]>
[2023-09-19T13:38:50.119+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-04T00:00:00+00:00 [queued]>
[2023-09-19T13:38:50.120+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-19T13:38:50.133+0000] {taskinstance.py:1380} INFO - Executing <Task(FileSensor): waiting_file> on 2023-09-04 00:00:00+00:00
[2023-09-19T13:38:50.138+0000] {standard_task_runner.py:57} INFO - Started process 1681 to run task
[2023-09-19T13:38:50.141+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '7.3-externalTaskSensor', 'waiting_file', 'scheduled__2023-09-04T00:00:00+00:00', '--job-id', '623', '--raw', '--subdir', 'DAGS_FOLDER/7.3-ExternalTaskSensor.py', '--cfg-path', '/tmp/tmp7eiazoyj']
[2023-09-19T13:38:50.143+0000] {standard_task_runner.py:85} INFO - Job 623: Subtask waiting_file
[2023-09-19T13:38:50.190+0000] {task_command.py:415} INFO - Running <TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-04T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-19T13:38:50.279+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='7.3-externalTaskSensor' AIRFLOW_CTX_TASK_ID='waiting_file' AIRFLOW_CTX_EXECUTION_DATE='2023-09-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-04T00:00:00+00:00'
[2023-09-19T13:38:50.288+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-19T13:38:50.289+0000] {filesystem.py:64} INFO - Poking for file /tmp/file.txt
[2023-09-19T13:38:50.289+0000] {filesystem.py:69} INFO - Found File /tmp/file.txt last modified: 20230919133849
[2023-09-19T13:38:50.290+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-09-19T13:38:50.299+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=7.3-externalTaskSensor, task_id=waiting_file, execution_date=20230904T000000, start_date=20230919T133850, end_date=20230919T133850
[2023-09-19T13:38:50.354+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-19T13:38:50.382+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
