[2023-09-19T13:02:05.109+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-03T00:00:00+00:00 [queued]>
[2023-09-19T13:02:05.119+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-03T00:00:00+00:00 [queued]>
[2023-09-19T13:02:05.120+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-19T13:02:05.139+0000] {taskinstance.py:1380} INFO - Executing <Task(FileSensor): waiting_file> on 2023-09-03 00:00:00+00:00
[2023-09-19T13:02:05.145+0000] {standard_task_runner.py:57} INFO - Started process 1033 to run task
[2023-09-19T13:02:05.148+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '7.3-externalTaskSensor', 'waiting_file', 'scheduled__2023-09-03T00:00:00+00:00', '--job-id', '598', '--raw', '--subdir', 'DAGS_FOLDER/7.3-ExternalTaskSensor.py', '--cfg-path', '/tmp/tmpt0ib8oot']
[2023-09-19T13:02:05.149+0000] {standard_task_runner.py:85} INFO - Job 598: Subtask waiting_file
[2023-09-19T13:02:05.201+0000] {task_command.py:415} INFO - Running <TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-03T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-19T13:02:05.278+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='7.3-externalTaskSensor' AIRFLOW_CTX_TASK_ID='waiting_file' AIRFLOW_CTX_EXECUTION_DATE='2023-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-03T00:00:00+00:00'
[2023-09-19T13:02:05.296+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/filesystem.py", line 61, in poke
    hook = FSHook(self.fs_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/filesystem.py", line 38, in __init__
    conn = self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
[2023-09-19T13:02:05.300+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=7.3-externalTaskSensor, task_id=waiting_file, execution_date=20230903T000000, start_date=20230919T130205, end_date=20230919T130205
[2023-09-19T13:02:05.313+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 598 for task waiting_file (The conn_id `fs_default` isn't defined; 1033)
[2023-09-19T13:02:05.321+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-19T13:02:05.353+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-19T13:38:35.825+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-03T00:00:00+00:00 [queued]>
[2023-09-19T13:38:35.834+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-03T00:00:00+00:00 [queued]>
[2023-09-19T13:38:35.835+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-19T13:38:35.853+0000] {taskinstance.py:1380} INFO - Executing <Task(FileSensor): waiting_file> on 2023-09-03 00:00:00+00:00
[2023-09-19T13:38:35.858+0000] {standard_task_runner.py:57} INFO - Started process 1664 to run task
[2023-09-19T13:38:35.861+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '7.3-externalTaskSensor', 'waiting_file', 'scheduled__2023-09-03T00:00:00+00:00', '--job-id', '620', '--raw', '--subdir', 'DAGS_FOLDER/7.3-ExternalTaskSensor.py', '--cfg-path', '/tmp/tmpvsv0tsly']
[2023-09-19T13:38:35.863+0000] {standard_task_runner.py:85} INFO - Job 620: Subtask waiting_file
[2023-09-19T13:38:35.911+0000] {task_command.py:415} INFO - Running <TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-03T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-19T13:38:35.997+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='7.3-externalTaskSensor' AIRFLOW_CTX_TASK_ID='waiting_file' AIRFLOW_CTX_EXECUTION_DATE='2023-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-03T00:00:00+00:00'
[2023-09-19T13:38:36.009+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-19T13:38:36.010+0000] {filesystem.py:64} INFO - Poking for file /tmp/file.txt
[2023-09-19T13:38:36.011+0000] {filesystem.py:69} INFO - Found File /tmp/file.txt last modified: 20230919133834
[2023-09-19T13:38:36.011+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-09-19T13:38:36.021+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=7.3-externalTaskSensor, task_id=waiting_file, execution_date=20230903T000000, start_date=20230919T133835, end_date=20230919T133836
[2023-09-19T13:38:36.074+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-19T13:38:36.106+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
