[2023-09-19T13:02:31.483+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-05T00:00:00+00:00 [queued]>
[2023-09-19T13:02:31.493+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-05T00:00:00+00:00 [queued]>
[2023-09-19T13:02:31.493+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-19T13:02:31.515+0000] {taskinstance.py:1380} INFO - Executing <Task(FileSensor): waiting_file> on 2023-09-05 00:00:00+00:00
[2023-09-19T13:02:31.520+0000] {standard_task_runner.py:57} INFO - Started process 1053 to run task
[2023-09-19T13:02:31.524+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '7.3-externalTaskSensor', 'waiting_file', 'scheduled__2023-09-05T00:00:00+00:00', '--job-id', '602', '--raw', '--subdir', 'DAGS_FOLDER/7.3-ExternalTaskSensor.py', '--cfg-path', '/tmp/tmpbjhh030z']
[2023-09-19T13:02:31.525+0000] {standard_task_runner.py:85} INFO - Job 602: Subtask waiting_file
[2023-09-19T13:02:31.576+0000] {task_command.py:415} INFO - Running <TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-05T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-19T13:02:31.663+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='7.3-externalTaskSensor' AIRFLOW_CTX_TASK_ID='waiting_file' AIRFLOW_CTX_EXECUTION_DATE='2023-09-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-05T00:00:00+00:00'
[2023-09-19T13:02:31.680+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/filesystem.py", line 61, in poke
    hook = FSHook(self.fs_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/filesystem.py", line 38, in __init__
    conn = self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
[2023-09-19T13:02:31.685+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=7.3-externalTaskSensor, task_id=waiting_file, execution_date=20230905T000000, start_date=20230919T130231, end_date=20230919T130231
[2023-09-19T13:02:31.697+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 602 for task waiting_file (The conn_id `fs_default` isn't defined; 1053)
[2023-09-19T13:02:31.738+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-19T13:02:31.768+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-19T13:39:04.339+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-05T00:00:00+00:00 [queued]>
[2023-09-19T13:39:04.352+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-05T00:00:00+00:00 [queued]>
[2023-09-19T13:39:04.354+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-19T13:39:04.379+0000] {taskinstance.py:1380} INFO - Executing <Task(FileSensor): waiting_file> on 2023-09-05 00:00:00+00:00
[2023-09-19T13:39:04.389+0000] {standard_task_runner.py:57} INFO - Started process 1690 to run task
[2023-09-19T13:39:04.394+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '7.3-externalTaskSensor', 'waiting_file', 'scheduled__2023-09-05T00:00:00+00:00', '--job-id', '626', '--raw', '--subdir', 'DAGS_FOLDER/7.3-ExternalTaskSensor.py', '--cfg-path', '/tmp/tmp_prjc4yu']
[2023-09-19T13:39:04.397+0000] {standard_task_runner.py:85} INFO - Job 626: Subtask waiting_file
[2023-09-19T13:39:04.464+0000] {task_command.py:415} INFO - Running <TaskInstance: 7.3-externalTaskSensor.waiting_file scheduled__2023-09-05T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-19T13:39:04.561+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='7.3-externalTaskSensor' AIRFLOW_CTX_TASK_ID='waiting_file' AIRFLOW_CTX_EXECUTION_DATE='2023-09-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-05T00:00:00+00:00'
[2023-09-19T13:39:04.572+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-19T13:39:04.572+0000] {filesystem.py:64} INFO - Poking for file /tmp/file.txt
[2023-09-19T13:39:04.573+0000] {filesystem.py:69} INFO - Found File /tmp/file.txt last modified: 20230919133903
[2023-09-19T13:39:04.574+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-09-19T13:39:04.585+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=7.3-externalTaskSensor, task_id=waiting_file, execution_date=20230905T000000, start_date=20230919T133904, end_date=20230919T133904
[2023-09-19T13:39:04.611+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-19T13:39:04.640+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
