[2023-09-18T13:49:41.689+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1-monitoring.task4 scheduled__2023-08-24T00:00:00+00:00 [queued]>
[2023-09-18T13:49:41.710+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1-monitoring.task4 scheduled__2023-08-24T00:00:00+00:00 [queued]>
[2023-09-18T13:49:41.711+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:49:41.728+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): task4> on 2023-08-24 00:00:00+00:00
[2023-09-18T13:49:41.734+0000] {standard_task_runner.py:57} INFO - Started process 4537 to run task
[2023-09-18T13:49:41.737+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoring', 'task4', 'scheduled__2023-08-24T00:00:00+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmpzq6y5e7m']
[2023-09-18T13:49:41.739+0000] {standard_task_runner.py:85} INFO - Job 267: Subtask task4
[2023-09-18T13:49:41.792+0000] {task_command.py:415} INFO - Running <TaskInstance: 6.1-monitoring.task4 scheduled__2023-08-24T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-18T13:49:41.876+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='6.1-monitoring' AIRFLOW_CTX_TASK_ID='task4' AIRFLOW_CTX_EXECUTION_DATE='2023-08-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-24T00:00:00+00:00'
[2023-09-18T13:49:41.881+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/6.1-monitoring.py", line 8, in myfunction
    raise Exception
Exception
[2023-09-18T13:49:41.898+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=6.1-monitoring, task_id=task4, execution_date=20230824T000000, start_date=20230918T134941, end_date=20230918T134941
[2023-09-18T13:49:41.912+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 267 for task task4 (; 4537)
[2023-09-18T13:49:41.950+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-18T13:49:41.974+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-18T13:52:19.105+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1-monitoring.task4 scheduled__2023-08-24T00:00:00+00:00 [queued]>
[2023-09-18T13:52:19.144+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1-monitoring.task4 scheduled__2023-08-24T00:00:00+00:00 [queued]>
[2023-09-18T13:52:19.145+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:52:19.195+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): task4> on 2023-08-24 00:00:00+00:00
[2023-09-18T13:52:19.202+0000] {standard_task_runner.py:57} INFO - Started process 4841 to run task
[2023-09-18T13:52:19.209+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoring', 'task4', 'scheduled__2023-08-24T00:00:00+00:00', '--job-id', '339', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmpt9mnp2gq']
[2023-09-18T13:52:19.214+0000] {standard_task_runner.py:85} INFO - Job 339: Subtask task4
[2023-09-18T13:52:19.318+0000] {task_command.py:415} INFO - Running <TaskInstance: 6.1-monitoring.task4 scheduled__2023-08-24T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-18T13:52:19.477+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='6.1-monitoring' AIRFLOW_CTX_TASK_ID='task4' AIRFLOW_CTX_EXECUTION_DATE='2023-08-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-24T00:00:00+00:00'
[2023-09-18T13:52:19.479+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-09-18T13:52:19.498+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=6.1-monitoring, task_id=task4, execution_date=20230824T000000, start_date=20230918T135219, end_date=20230918T135219
[2023-09-18T13:52:19.544+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-18T13:52:19.601+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
