[2023-09-18T13:51:35.304+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1-monitoring.task4 scheduled__2023-08-14T00:00:00+00:00 [queued]>
[2023-09-18T13:51:35.405+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1-monitoring.task4 scheduled__2023-08-14T00:00:00+00:00 [queued]>
[2023-09-18T13:51:35.406+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:51:35.466+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): task4> on 2023-08-14 00:00:00+00:00
[2023-09-18T13:51:35.477+0000] {standard_task_runner.py:57} INFO - Started process 4702 to run task
[2023-09-18T13:51:35.515+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoring', 'task4', 'scheduled__2023-08-14T00:00:00+00:00', '--job-id', '300', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmp6r1pm1n7']
[2023-09-18T13:51:35.519+0000] {standard_task_runner.py:85} INFO - Job 300: Subtask task4
[2023-09-18T13:51:53.747+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 300 for task task4 ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 4702)
[2023-09-18T13:51:57.426+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-18T13:51:57.563+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
